org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.241
loader_version_range=[4,)
mod_id=originsmodernui
mod_name=Origin Architect
mod_license=MIT
mod_version=5.2.2
mod_group_id=ro.vlad.originsmodernui
